### PR TITLE
 Add support for react native 

### PR DESCRIPTION
**Pull request by clentfort**
**Summary:**

React Native handles files differently than browsers.

### CODE REVIEW

**Comment by richeterre** [comment]
Hey @clentfort, thanks for opening this! Looks like `yarn install` fails for me on this branch because of a TS linter error:

```
$ yarn run tslint --type-check -p .
$ /Users/Martin/Library/Caches/Yarn/v1/.tmp/60183b7238a75ed3a8e8023154721225.0ad8f496469a23c2f30debfcb6c50a9d457f765f.prepare/node_modules/.bin/tslint --type-check -p .

ERROR: /Users/Martin/Library/Caches/Yarn/v1/.tmp/60183b7238a75ed3a8e8023154721225.0ad8f496469a23c2f30debfcb6c50a9d457f765f.prepare/src/index.ts[7, 6]: Use an interface instead of a type literal.
```

**Comment by clentfort** [comment]
Sorry about that, I though I had run `yarn lint`. Can you check with the latest commit added?

**Comment by richeterre** [comment]
Now it compiles, but uploading doesn't work. My theory is that we do actually need a class (not a type or interface) because in the client I'm doing this:

```js
const file = new ReactNativeFile({
  uri: image.path,
  type: image.mime,
  name: image.filename || 'unknown',
})

runSomeMutation({
  variables: {
    picture: file,
  },
})
```

and with the latest commit it crashes as there is no class to instantiate.

**Comment by richeterre** [comment]
Ah, now I saw your updated tests and realized that I can replace that `new ReactNativeFile` by a plain object with those three attributes. With that change it works ☺️

I guess the downside of this approach is that it leaves the required format pretty implicit, especially if you don't export the type/interface for others to use. I basically have to know that exactly those three attributes are required.

Edit: Check out [this comment](https://github.com/jaydenseric/apollo-upload-client/pull/17#issuecomment-310805785) for the rationale behind introducing this class in `apollo-upload-client`. But personally I'm fine with the current solution, too.

**Comment by clentfort** [comment]
Actually only `uri` is required, but after reading the linked thread I can see how this could have unwanted side-effects if I only check for the existence of the `uri`-attribute. Sorry for putting all this burden on you.

**Comment by clentfort** [comment]
So my plan is, to reintroduce the `ReactNativeFile` class as you initially proposed. Again sorry.

**Comment by richeterre** [comment]
No problem! I'm not super experienced with any of this stuff yet (last year I was still a native iOS developer with basically zero JS experience), so I'm just trying to make sense of what I find in various repos and libraries 😄

**Comment by clentfort** [comment]
I'm a bit hesitant to add a new class that people must use to support react native. Would a custom `isFile`-option suit your needs?

I'm thinking about something like the following: It would free us of shipping and maintaining react native code and would allow anyone to extend the file matching to suit their needs.

```ts
import {
  createNetworkInterface,
  isFile as isFileBase,
  UploadFileType,
} from "apollo-absinthe-upload-client";

class ReactNativeFile {
   ...
}

function isFile(value: any): value is UploadFileType {
  return isFileBase(value) || value instanceof ReactNativeFile;
}

const networkInterface = createNetworkInterface({ isFile });
```

**Comment by richeterre** [comment]
I'll gladly give it a try with my app if you update the branch, much appreciated! 😊 I understand you don't want to couple your lib too closely to RN, although I'm not sure if this really would require much "maintenance" at all…

**Comment by clentfort** [comment]
Hey, sorry for the late response. Would the new API proposed in the latest commit work for you?

You could change your code like the following:

```ts
import {
    UploadFileType,
    createNetworkInterface
} from "apollo-absinthe-upload-client";
import { ReactNativeFile } from "somewhere";

function isReactNativeUploadFile(value: any): value is UploadFile {
    return value instanceof ReactNativeFile;
}

createNetworkInterface({
    uri: "/graphql",
    isUploadFile: isReactNativeUploadFile
});
```

**Comment by richeterre** [comment]
Hi, apologies for the late response 🙇 I'm currently at a conference abroad, but will check it out this weekend!

**Comment by richeterre** [comment]
Hey @clentfort, works for me! 👍 Let's get this merged in!

**Pull request merged**
